teleop_twist_joy_node:
  ros__parameters:
    use_sim_time: true
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:  # Left thumb stick horizontal
      yaw: 0
    scale_angular:
      yaw: 0.4

    enable_button: 4  # Left trigger button
    enable_turbo_button: 5  # Right trigger button

gz_ros_control:
  ros__parameters:
    use_sim_time: True

rviz2:
  ros__parameters:
    use_sim_time: True

joy_node:
  ros__parameters:
    use_sim_time: True
